### ISSUE TITLE
Thanks with feedback

### ISSUE THREAD

**Issue by plokhotnyuk** [mikepapadim/llama2.tornadovm.java#1]
@mikepapadim Thanks for the great sample of TornadoVM usage!

Tested it with Intel CUDA drivers on Dell XPS laptop with  Intel® Core™ i7-11800H CPU:

![image](https://github.com/mikepapadim/llama2.tornadovm.java/assets/890289/1bee98ed-7541-44f2-a30b-5cb2822fdec9)

Beside mentioned prerequisites it required installation of `maven` and OpenCL drivers for Intel GPU for my case.

Also, a couple of modifications for `set_paths.sh` and `pom.xml` files were required to allow `tornado` command and use `LATEST` version of TornadoVM.

Would you accept a PR with updates for that?

**Comment by mikepapadim** [comment]
Thank you for the feedback @plokhotnyuk. Feel free to open a PR with the changes.
